package org.bian.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.bian.dto.SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceAgreement;
import org.bian.dto.SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceConfigurationSetup;
import org.bian.dto.SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceSubscription;

import javax.validation.Valid;
  
/**
 * SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecord
 */
public class SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecord   {
  private String productInventoryDistributionServiceConfigurationSettingReference = null;

  private String productInventoryDistributionServiceConfigurationSettingType = null;

  private SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceConfigurationSetup productInventoryDistributionServiceConfigurationSetup = null;

  private SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceSubscription productInventoryDistributionServiceSubscription = null;

  private SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceAgreement productInventoryDistributionServiceAgreement = null;


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Refers to the service configuration parameter for the service 
   * @return productInventoryDistributionServiceConfigurationSettingReference
  **/

  public String getProductInventoryDistributionServiceConfigurationSettingReference() {
    return productInventoryDistributionServiceConfigurationSettingReference;
  }

  public void setProductInventoryDistributionServiceConfigurationSettingReference(String productInventoryDistributionServiceConfigurationSettingReference) {
    this.productInventoryDistributionServiceConfigurationSettingReference = productInventoryDistributionServiceConfigurationSettingReference;
  }


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The type of service configuration parameter 
   * @return productInventoryDistributionServiceConfigurationSettingType
  **/

  public String getProductInventoryDistributionServiceConfigurationSettingType() {
    return productInventoryDistributionServiceConfigurationSettingType;
  }

  public void setProductInventoryDistributionServiceConfigurationSettingType(String productInventoryDistributionServiceConfigurationSettingType) {
    this.productInventoryDistributionServiceConfigurationSettingType = productInventoryDistributionServiceConfigurationSettingType;
  }


  /**
   * Get productInventoryDistributionServiceConfigurationSetup
   * @return productInventoryDistributionServiceConfigurationSetup
  **/

  public SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceConfigurationSetup getProductInventoryDistributionServiceConfigurationSetup() {
    return productInventoryDistributionServiceConfigurationSetup;
  }

  public void setProductInventoryDistributionServiceConfigurationSetup(SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceConfigurationSetup productInventoryDistributionServiceConfigurationSetup) {
    this.productInventoryDistributionServiceConfigurationSetup = productInventoryDistributionServiceConfigurationSetup;
  }


  /**
   * Get productInventoryDistributionServiceSubscription
   * @return productInventoryDistributionServiceSubscription
  **/

  public SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceSubscription getProductInventoryDistributionServiceSubscription() {
    return productInventoryDistributionServiceSubscription;
  }

  public void setProductInventoryDistributionServiceSubscription(SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceSubscription productInventoryDistributionServiceSubscription) {
    this.productInventoryDistributionServiceSubscription = productInventoryDistributionServiceSubscription;
  }


  /**
   * Get productInventoryDistributionServiceAgreement
   * @return productInventoryDistributionServiceAgreement
  **/

  public SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceAgreement getProductInventoryDistributionServiceAgreement() {
    return productInventoryDistributionServiceAgreement;
  }

  public void setProductInventoryDistributionServiceAgreement(SDProductInventoryDistributionConfigureInputModelProductInventoryDistributionServiceConfigurationRecordProductInventoryDistributionServiceAgreement productInventoryDistributionServiceAgreement) {
    this.productInventoryDistributionServiceAgreement = productInventoryDistributionServiceAgreement;
  }


}

